spring:
  application:
    name: todoapp
  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/schema.sql
  datasource:
    username: myuser
    password: secret
    url: jdbc:postgresql://localhost:32781/postgres
    driver-class-name: org.postgresql.Driver
