# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Jon Breid

spring:
  application:
    name: todoapp
  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/schema.sql
  datasource:
    username: myuser
    password: secret
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
JWT_SECRET: my-secret-and-long-and-very-secret-dev-placeholder-key